<?php
/**
* @ iDezender 8.0
* @ Developed by Qarizma
*
* @    Visit our website:
* @    www.iRadikal.com
* @    For cheap decoding service :)
* @    And for the ionCube Decoder!
*/          

	require_once( '../include/startup.php' );
	echo 'Starting';
	udbrollbacktransaction(  );
	$q = '';
	$q .= 'clCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'clType				INT,';
	$q .= 'clName				VARCHAR(200),';
	$q .= 'clFirstName		VARCHAR(200),';
	$q .= 'clLastName			VARCHAR(200),';
	$q .= 'clNameSort			VARCHAR(200),';
	$q .= 'clInitials			VARCHAR(20),';
	$q .= 'clTitle			INT,';
	$q .= 'clSalutation		VARCHAR(40),';
	$q .= 'clPosition			VARCHAR(200),';
	$q .= 'clSex				CHAR(1),';
	$q .= 'clMaritalStatus	INT,';
	$q .= 'clSourceOfBus		INT,';
	$q .= 'clSpouseName		VARCHAR(200),';
	$q .= 'clNonSmoker		INT,';
	$q .= 'clHomeOwner		INT,';
	$q .= 'clNewBusiness		INT,';
	$q .= 'clDOB				DATE,';
	$q .= 'clClientSince		DATE,';
	$q .= 'clAddress			TEXT,';
	$q .= 'clInvAddress		INT,';
	$q .= 'clWhenUpdated		CHAR(14),';
	$q .= 'clUpdatedBy		INT,';
	$q .= 'clPostcode			VARCHAR(50),';
	$q .= 'clCountry			VARCHAR(100),';
	$q .= 'clHomePhone		VARCHAR(100),';
	$q .= 'clWorkPhone		VARCHAR(100),';
	$q .= 'clEmail			VARCHAR(100),';
	$q .= 'clMobile			VARCHAR(100),';
	$q .= 'clFax				VARCHAR(100),';
	$q .= 'clDiscount			INT,';
	$q .= 'clDurable			INT,';
	$q .= 'clDurableDate		DATE,';
	$q .= 'clBrStatus			DATE,';
	$q .= 'clStatementType	INT,';
	$q .= 'clContactEmail		VARCHAR(100),';
	$q .= 'clContactMobile	VARCHAR(100),';
	$q .= 'clContactFax		VARCHAR(100),';
	$q .= 'clStatus			INT,';
	$q .= 'clStatusDate		DATE,';
	$q .= 'clIntroducer		INT,';
	$q .= 'clWebsite			VARCHAR(100),';
	$q .= 'clBusinessTrade	VARCHAR(100),';
	$q .= 'clBusinessDesc		TEXT,';
	$q .= 'clHandler			INT,';
	$q .= 'clInvAddTitle		INT,';
	$q .= 'clInvAddFirstName	VARCHAR(200),';
	$q .= 'clInvAddLastName	VARCHAR(200),';
	$q .= 'clInvAddSalutation	VARCHAR(40),';
	$q .= 'clInvAddPosition	VARCHAR(200),';
	$q .= 'clInvAddAddress	TEXT,';
	$q .= 'clInvAddPostcode	VARCHAR(50),';
	$q .= 'clInvAddCountry	VARCHAR(100),';
	$q .= 'clInvAddWorkPhone	VARCHAR(100),';
	$q .= 'clInvAddMobile		VARCHAR(100),';
	$q .= 'clInvAddEmail		VARCHAR(100),';
	$q .= 'clInvAddFax		VARCHAR(100),';
	$q .= 'clLastUpdateBy		INT,';
	$q .= 'clLastUpdateOn		CHAR(14),';
	$q .= 'lastAccessTime		CHAR(14))';
	udbcreatetable( 'clients', $q );
	$q = 'ALTER TABLE clients AUTO_INCREMENT = 2000000';
	$result = mysql_query( $q );

	if ($result == null) {
		exit( 'cat set auto increment on clients' );
	}

	udbcreateindex( 'clients', 'clTypeIndex', 'clType' );
	udbcreateindex( 'clients', 'clNameIndex', 'clName' );
	udbcreateindex( 'clients', 'clFirstNameIndex', 'clFirstName' );
	udbcreateindex( 'clients', 'clLastNameIndex', 'clLastName' );
	udbcreateindex( 'clients', 'clBusinessTradeIndex', 'clBusinessTrade' );
	$q = '';
	$q .= 'plCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'plClient			INT,';
	$q .= 'plInsCo			INT,';
	$q .= 'plHandler			INT,';
	$q .= 'plAltInsCo			INT,';
	$q .= 'plFrequency		INT,';
	$q .= 'plPolicyType		CHAR(1),';
	$q .= 'plPolicyHolder		VARCHAR(200),';
	$q .= 'plPolicyNumber		VARCHAR(50),';
	$q .= 'plInceptionDate	DATE,';
	$q .= 'plRenewalDate		DATE,';
	$q .= 'plPrevRenewalDate	DATE,';
	$q .= 'plPaymentDate		DATE,';
	$q .= 'plEnquiryDate		DATE,';
	$q .= 'plTORDate			DATE,';
	$q .= 'plPremium			BIGINT,';
	$q .= 'plAddnPremium		BIGINT,';
	$q .= 'plOthers			BIGINT,';
	$q .= 'plTotalPremium		BIGINT,';
	$q .= 'plCoverDescription	VARCHAR(200),';
	$q .= 'plPrevCoverDesc	TEXT,';
	$q .= 'plClassOfBus		INT,';
	$q .= 'plSourceOfBus		INT,';
	$q .= 'plSaleMethod		INT,';
	$q .= 'plPaymentMethod	INT,';
	$q .= 'plDirect			INT,';
	$q .= 'plStatus			INT DEFAULT 0,';
	$q .= 'plStatusDate		DATE,';
	$q .= 'plSourceDocm		VARCHAR(200),';
	$q .= 'plNewBusiness		INT,';
	$q .= 'plIntrodComm		INT,';
	$q .= 'plClientDisc		INT,';
	$q .= 'plPolDocsDue		INT,';
	$q .= 'plDurable			INT,';
	$q .= 'plDurableDate		DATE,';
	$q .= 'plBrStatus			DATE,';
	$q .= 'plGrossIncIPT		BIGINT,';
	$q .= 'plGross			BIGINT,';
	$q .= 'plCommissionRate	BIGINT,';
	$q .= 'plCommission		BIGINT,';
	$q .= 'plNet				BIGINT,';
	$q .= 'plIPTRate			BIGINT,';
	$q .= 'plGrossIPT			BIGINT,';
	$q .= 'plAddlCoverDesc			VARCHAR(100),';
	$q .= 'plAddlGrossIncIPT			BIGINT,';
	$q .= 'plAddlGross			BIGINT,';
	$q .= 'plAddlCommissionRate	BIGINT,';
	$q .= 'plAddlCommission		BIGINT,';
	$q .= 'plAddlNet				BIGINT,';
	$q .= 'plAddlIPT				BIGINT,';
	$q .= 'plAddOnCoverDescription	VARCHAR(200),';
	$q .= 'plAddOnGrossIncIPT			BIGINT,';
	$q .= 'plAddOnGross			BIGINT,';
	$q .= 'plAddOnCommissionRate	BIGINT,';
	$q .= 'plAddOnCommission		BIGINT,';
	$q .= 'plAddOnNet				BIGINT,';
	$q .= 'plAddOnIPTRate			BIGINT,';
	$q .= 'plAddOnIPT				BIGINT,';
	$q .= 'plClientDiscountRate	BIGINT,';
	$q .= 'plClientDiscount		BIGINT,';
	$q .= 'plEngineeringFeeDesc		VARCHAR(200),';
	$q .= 'plEngineeringFee			BIGINT,';
	$q .= 'plEngineeringFeeCommRate	BIGINT,';
	$q .= 'plEngineeringFeeComm		BIGINT,';
	$q .= 'plEngineeringFeeNet		BIGINT,';
	$q .= 'plEngineeringFeeVATRate	BIGINT,';
	$q .= 'plEngineeringFeeVAT		BIGINT,';
	$q .= 'plBrokerFee				BIGINT,';
	$q .= 'plBrokerFeeVATRate			BIGINT,';
	$q .= 'plBrokerFeeVAT				BIGINT,';
	$q .= 'plIntroducerCommRate		BIGINT,';
	$q .= 'plIntroducerComm			BIGINT,';
	$q .= 'plTotalGross			BIGINT,';
	$q .= 'plTotalGrossIncIPT		BIGINT,';
	$q .= 'plTotalCommission		BIGINT,';
	$q .= 'plTotalNet				BIGINT,';
	$q .= 'plTotalIPT				BIGINT,';
	$q .= 'plClientSubTotal			BIGINT,';
	$q .= 'plClientTotal			BIGINT,';
	$q .= 'plBrokerSubTotal		BIGINT,';
	$q .= 'plBrokerTotal			BIGINT,';
	$q .= 'plInsCoTotal			BIGINT,';
	$q .= 'plAddOnTotal			BIGINT,';
	$q .= 'plPolicyTotal			BIGINT,';
	$q .= 'plDirectClientTotal	BIGINT,';
	$q .= 'plDirectClientGrand	BIGINT,';
	$q .= 'plDirectBrokerTotal	BIGINT,';
	$q .= 'plTotalInstalmentComm	BIGINT,';
	$q .= 'plLastUpdateBy			INT,';
	$q .= 'plLastUpdateOn			CHAR(14),';
	$q .= 'plJBSequence			INT,';
	$q .= 'lastAccessTime		CHAR(14))';
	udbcreatetable( 'policies', $q );
	$q = 'ALTER TABLE policies AUTO_INCREMENT = 3000000';
	$result = mysql_query( $q );

	if ($result == null) {
		exit( 'cat set auto increment on policies' );
	}

	$q = '';
	$q .= 'icCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'icName			VARCHAR(100),';
	$q .= 'icType			INT,';
	$q .= 'icAddress		TEXT,';
	$q .= 'icPostcode		VARCHAR(50),';
	$q .= 'icCountry		VARCHAR(100),';
	$q .= 'icBranch			VARCHAR(100),';
	$q .= 'icInvAddress		INT,';
	$q .= 'icAgencyNo		VARCHAR(50),';
	$q .= 'icFax			VARCHAR(100),';
	$q .= 'icPhone			VARCHAR(100),';
	$q .= 'icContact		VARCHAR(100),';
	$q .= 'icEmail			VARCHAR(100),';
	$q .= 'icWebsite		VARCHAR(100),';
	$q .= 'icAddonCOB		INT,';
	$q .= 'icStatus			INT,';
	$q .= 'icDeptName1		VARCHAR(100),';
	$q .= 'icDeptContact1	VARCHAR(100),';
	$q .= 'icDeptPhone1		VARCHAR(100),';
	$q .= 'icDeptEmail1		VARCHAR(100),';
	$q .= 'icDeptName2		VARCHAR(100),';
	$q .= 'icDeptContact2	VARCHAR(100),';
	$q .= 'icDeptPhone2		VARCHAR(100),';
	$q .= 'icDeptEmail2		VARCHAR(100),';
	$q .= 'icAccTitle		INT,';
	$q .= 'icAccFirstName	VARCHAR(50),';
	$q .= 'icAccLastName	VARCHAR(50),';
	$q .= 'icAccSalutation	VARCHAR(50),';
	$q .= 'icAccPosition	VARCHAR(50),';
	$q .= 'icAccAddress		TEXT,';
	$q .= 'icAccCountry		VARCHAR(50),';
	$q .= 'icAccPostcode	VARCHAR(20),';
	$q .= 'icAccPhone		VARCHAR(50),';
	$q .= 'icAccMobile		VARCHAR(50),';
	$q .= 'icAccEmail		VARCHAR(50),';
	$q .= 'icAccFax			VARCHAR(50),';
	$q .= 'icDelegated		INT,';
	$q .= 'icIPTAmendable		INT,';
	$q .= 'icLastUpdateBy	INT,';
	$q .= 'icLastUpdateOn	CHAR(14),';
	$q .= 'lastAccessTime	CHAR(14))';
	udbcreatetable( 'insuranceCompanies', $q );
	$q = 'ALTER TABLE insuranceCompanies AUTO_INCREMENT = 1000000';
	$result = mysql_query( $q );

	if ($result == null) {
		exit( 'cat set auto increment on insuranceCompaniess' );
	}

	$q = '';
	$q .= 'iyCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'iyName			VARCHAR(100),';
	$q .= 'iySequence		INT)';
	udbcreatetable( 'insCoTypes', $q );
	$q = '';
	$q .= 'inCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'inName			VARCHAR(100),';
	$q .= 'inAddress		TEXT,';
	$q .= 'inPostcode		VARCHAR(50),';
	$q .= 'inCountry		VARCHAR(100),';
	$q .= 'inFax			VARCHAR(100),';
	$q .= 'inBranch			VARCHAR(100),';
	$q .= 'inPhone			VARCHAR(100),';
	$q .= 'inDepartment		VARCHAR(100),';
	$q .= 'inContact		VARCHAR(100),';
	$q .= 'inContactPhone	VARCHAR(100),';
	$q .= 'inEmail			VARCHAR(100),';
	$q .= 'inSinceDate		DATE,';
	$q .= 'inTerms			CHAR(1),';
	$q .= 'inRate			BIGINT,';
	$q .= 'inFlatRate		BIGINT,';
	$q .= 'inApplyToAll		INT,';
	$q .= 'inWebsite		VARCHAR(100),';
	$q .= 'inStatus			INT,';
	$q .= 'inStatementType	INT,';
	$q .= 'inDurable		INT,';
	$q .= 'inAccTitle		INT,';
	$q .= 'inAccFirstName	VARCHAR(50),';
	$q .= 'inAccLastName	VARCHAR(50),';
	$q .= 'inAccSalutation	VARCHAR(50),';
	$q .= 'inAccPosition	VARCHAR(50),';
	$q .= 'inAccAddress		TEXT,';
	$q .= 'inAccCountry		VARCHAR(50),';
	$q .= 'inAccPostcode	VARCHAR(20),';
	$q .= 'inAccPhone		VARCHAR(50),';
	$q .= 'inAccMobile		VARCHAR(50),';
	$q .= 'inAccEmail		VARCHAR(50),';
	$q .= 'inAccFax			VARCHAR(50),';
	$q .= 'inLastUpdateBy	INT,';
	$q .= 'inLastUpdateOn	CHAR(14),';
	$q .= 'lastAccessTime	CHAR(14))';
	udbcreatetable( 'introducers', $q );
	$q = 'ALTER TABLE introducers AUTO_INCREMENT = 8000000';
	$result = mysql_query( $q );

	if ($result == null) {
		exit( 'cat set auto increment on introducers' );
	}

	$q = '';
	$q .= 'sqCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'sqType				VARCHAR(10),';
	$q .= 'sqMaster			INT,';
	$q .= 'sqLastUsed			INT DEFAULT 0)';
	udbcreatetable( 'sequences', $q );
	udbcreateindex( 'sequences', 'sqTypeIndex', 'sqType' );
	udbcreateindex( 'sequences', 'sqMasterIndex', 'sqMaster' );
	udbcreateindex( 'sequences', 'sqLastUsedIndex', 'sqLastUsed' );
	$seq = new Sequence( null );
	$seq->set( 'sqType', 'PTI' );
	$seq->set( 'sqMaster', 1 );
	$seq->set( 'sqLastUsed', 2999999 );
	$seq->insert( null );
	$q = '';
	$q .= 'noCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'noClient			INT,';
	$q .= 'noPolicy			INT,';
	$q .= 'noInsco			INT,';
	$q .= 'noIntroducer		INT,';
	$q .= 'noClientSequence	INT,';
	$q .= 'noPolicySequence	INT,';
	$q .= 'noInscoSequence	INT,';
	$q .= 'noIntroducerSequence	INT,';
	$q .= 'noType				INT,';
	$q .= 'noLocked			BOOL,';
	$q .= 'noWhenOriginated	CHAR(14),';
	$q .= 'noOriginator		INT,';
	$q .= 'noWhenEntered		CHAR(14),';
	$q .= 'noEnteredBy		INT,';
	$q .= 'noUpdateorCreate	CHAR(14),';
	$q .= 'noNextActionBy		INT,';
	$q .= 'noSubject			VARCHAR(200),';
	$q .= 'noNote				TEXT,';
	$q .= 'lastAccessTime		CHAR(14))';
	udbcreatetable( 'notes', $q );
	udbcreateindex( 'notes', 'noClientIndex', 'noClient' );
	udbcreateindex( 'notes', 'noPolicyIndex', 'noPolicy' );
	udbcreateindex( 'notes', 'noInscoIndex', 'noInsco' );
	udbcreateindex( 'notes', 'noIntroducerIndex', 'noIntroducer' );
	udbcreateindex( 'notes', 'noWhenEnteredIndex', 'noWhenEntered' );
	$q = 'ALTER TABLE notes AUTO_INCREMENT = 5000000';
	$result = mysql_query( $q );

	if ($result == null) {
		exit( 'cat set auto increment on notes' );
	}

	$q = '';
	$q .= 'doCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'doClient			INT,';
	$q .= 'doPolicy			INT,';
	$q .= 'doInsco			INT,';
	$q .= 'doIntroducer		INT,';
	$q .= 'doTrans			INT,';
	$q .= 'doSysTran			INT,';
	$q .= 'doClientSequence	INT,';
	$q .= 'doPolicySequence	INT,';
	$q .= 'doInscoSequence	INT,';
	$q .= 'doIntroducerSequence INT,';
	$q .= 'doTransSequence	INT,';
	$q .= 'doDocmType			INT,';
	$q .= 'doUploadType		INT,';
	$q .= 'doLocked			BOOL,';
	$q .= 'doWhenOriginated	CHAR(14),';
	$q .= 'doOriginator		INT,';
	$q .= 'doWhenEntered		CHAR(14),';
	$q .= 'doEnteredBy		INT,';
	$q .= 'doClientSentWhen	DATE,';
	$q .= 'doClientSentHow	INT,';
	$q .= 'doClientSentBy		INT,';
	$q .= 'doClientAttachedTo	INT,';
	$q .= 'doInscoSentWhen	DATE,';
	$q .= 'doInscoSentHow		INT,';
	$q .= 'doInscoSentBy		INT,';
	$q .= 'doInscoAttachedTo	INT,';
	$q .= 'doIntroducerSentWhen	DATE,';
	$q .= 'doIntroducerSentHow	INT,';
	$q .= 'doIntroducerSentBy		INT,';
	$q .= 'doIntroducerAttachedTo	INT,';
	$q .= 'doUpdateorCreate	CHAR(14),';
	$q .= 'doNextActionBy		INT,';
	$q .= 'doSubject			VARCHAR(200),';
	$q .= 'doFileSize			INT,';
	$q .= 'doFileType			VARCHAR(100),';
	$q .= 'doFileName			VARCHAR(200),';
	$q .= 'doBinaryDetail		LONGBLOB,';
	$q .= 'doDeleted			BOOL DEFAULT 0,';
	$q .= 'lastAccessTime		CHAR(14))';
	udbcreatetable( 'documents', $q );
	udbcreateindex( 'documents', 'dolientIndex', 'doClient' );
	udbcreateindex( 'documents', 'doPolicyIndex', 'doPolicy' );
	udbcreateindex( 'documents', 'doInscoIndex', 'doInsco' );
	udbcreateindex( 'documents', 'doIntroducerIndex', 'doIntroducer' );
	udbcreateindex( 'documents', 'doDocmTypeIndex', 'doDocmType' );
	udbsettablefortransactions( 'documents' );
	$q = 'ALTER TABLE documents AUTO_INCREMENT = 6000000';
	$result = mysql_query( $q );

	if ($result == null) {
		exit( 'cat set auto increment on documents' );
	}

	$q = '';
	$q .= 'csCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'csName			VARCHAR(100),';
	$q .= 'csLocked			BOOL,';
	$q .= 'csSequence		INT)';
	udbcreatetable( 'clientStatus', $q );
	$q = '';
	$q .= 'stCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'stName			VARCHAR(100),';
	$q .= 'stSequence		INT)';
	udbcreatetable( 'policyStatus', $q );
	$q = '';
	$q .= 'cbCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'cbName			VARCHAR(100),';
	$q .= 'cbFullName		VARCHAR(200),';
	$q .= 'cbIsTravel		BOOL,';
	$q .= 'cbFeesVatable	BOOL,';
	$q .= 'cbRMAR			BOOL,';
	$q .= 'cbZeroIPT		BOOL,';
	$q .= 'cbAllowIPTAmend	BOOL,';
	$q .= 'cbSequence		INT)';
	udbcreatetable( 'classOfBus', $q );
	$q = '';
	$q .= 'cyCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'cyName			VARCHAR(100),';
	$q .= 'cySequence		INT)';
	udbcreatetable( 'clientTypes', $q );
	$q = '';
	$q .= 'msCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'msName			VARCHAR(100),';
	$q .= 'msSequence		INT)';
	udbcreatetable( 'maritalStatus', $q );
	$q = '';
	$q .= 'tiCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'tiName			VARCHAR(100),';
	$q .= 'tiSequence		INT)';
	udbcreatetable( 'titles', $q );
	$q = '';
	$q .= 'sbCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'sbName			VARCHAR(100),';
	$q .= 'sbSequence		INT)';
	udbcreatetable( 'sourceOfBus', $q );
	$q = '';
	$q .= 'cmCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'cmName			VARCHAR(100),';
	$q .= 'cmFax			BOOL,';
	$q .= 'cmEmail			BOOL,';
	$q .= 'cmPost			BOOL,';
	$q .= 'cmSequence		INT)';
	udbcreatetable( 'communMethod', $q );
	$q = '';
	$q .= 'psCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'psName			VARCHAR(100),';
	$q .= 'psSequence		INT)';
	udbcreatetable( 'policySaleMethods', $q );
	$q = '';
	$q .= 'pmCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'pmName			VARCHAR(100),';
	$q .= 'pmDirect			BOOL,';
	$q .= 'pmSequence		INT)';
	udbcreatetable( 'policyPaymentMethods', $q );
	$q = '';
	$q .= 'hsCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'hsName			VARCHAR(100),';
	$q .= 'hsSequence		INT)';
	udbcreatetable( 'howSent', $q );
	$q = '';
	$q .= 'ntCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'ntName			VARCHAR(100),';
	$q .= 'ntClient			BOOL DEFAULT 0,';
	$q .= 'ntPolicy			BOOL DEFAULT 0,';
	$q .= 'ntInsco			BOOL DEFAULT 0,';
	$q .= 'ntIntroducer		BOOL DEFAULT 0,';
	$q .= 'ntSequence		INT)';
	udbcreatetable( 'noteTypes', $q );
	udbcreateindex( 'noteTypes', 'ntSequenceIndex', 'ntSequence' );
	$q = '';
	$q .= 'dtCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'dtName			VARCHAR(100),';
	$q .= 'dtClient			BOOL DEFAULT 0,';
	$q .= 'dtPolicy			BOOL DEFAULT 0,';
	$q .= 'dtInsco			BOOL DEFAULT 0,';
	$q .= 'dtIntroducer		BOOL DEFAULT 0,';
	$q .= 'dtSequence		INT)';
	udbcreatetable( 'documentTypes', $q );
	$q = '';
	$q .= 'dpCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'dpName			VARCHAR(100))';
	udbcreatetable( 'departments', $q );
	$q = '';
	$q .= 'tnCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'tnType			VARCHAR(10),';
	$q .= 'tnCreatedBy		INT,';
	$q .= 'tnCreatedOn		CHAR(14),';
	$q .= 'tnTran			INT)';
	udbcreatetable( 'systemTransactions', $q );
	$q = '';
	$q .= 'ssCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'ssSequence		INT )';
	udbcreatetable( 'systemSequeneces', $q );
	$q = '';
	$q .= 'ptCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'ptSysTran			INT,';
	$q .= 'ptPolicy			INT,';
	$q .= 'ptTransType		INT,';
	$q .= 'ptDebit			BOOL,';
	$q .= 'ptInvoiceNo		INT,';
	$q .= 'ptBrokerRef		VARCHAR(100),';
	$q .= 'ptInsCoRef			VARCHAR(100),';
	$q .= 'ptTransDesc		VARCHAR(250),';
	$q .= 'ptCoverDesc		TEXT,';
	$q .= 'ptPostingDate		DATE,';
	$q .= 'ptEffectiveFrom	DATE,';
	$q .= 'ptEffectiveTo		DATE,';
	$q .= 'ptAccountingYear	INT,';
	$q .= 'ptAccountingPeriod	INT,';
	$q .= 'ptClient			INT,';
	$q .= 'ptInsCo			INT,';
	$q .= 'ptHandler			INT,';
	$q .= 'ptAltInsCo			INT,';
	$q .= 'ptIntroducer		INT,';
	$q .= 'ptFrequency		INT,';
	$q .= 'ptPolicyType		CHAR(1),';
	$q .= 'ptPolicyNumber		VARCHAR(50),';
	$q .= 'ptPaymentDate		DATE,';
	$q .= 'ptPremium			BIGINT,';
	$q .= 'ptAddnPremium		BIGINT,';
	$q .= 'ptOthers			BIGINT,';
	$q .= 'ptTotalPremium		BIGINT,';
	$q .= 'ptCoverDescription	VARCHAR(200),';
	$q .= 'ptClassOfBus		INT,';
	$q .= 'ptSourceOfBus		INT,';
	$q .= 'ptSaleMethod		INT,';
	$q .= 'ptPaymentMethod	INT,';
	$q .= 'ptDirect			INT,';
	$q .= 'ptStatus			INT DEFAULT 0,';
	$q .= 'ptStatusDate		DATE,';
	$q .= 'ptNewBusiness		INT,';
	$q .= 'ptIntrodComm		INT,';
	$q .= 'ptClientDisc		INT,';
	$q .= 'ptPolDocsDue		INT,';
	$q .= 'ptGrossIncIPT		BIGINT,';
	$q .= 'ptGross			BIGINT,';
	$q .= 'ptCommissionRate	BIGINT,';
	$q .= 'ptCommission		BIGINT,';
	$q .= 'ptNet				BIGINT,';
	$q .= 'ptIPTRate			BIGINT,';
	$q .= 'ptGrossIPT			BIGINT,';
	$q .= 'ptAddlCoverDesc			VARCHAR(100),';
	$q .= 'ptAddlGrossIncIPT			BIGINT,';
	$q .= 'ptAddlGross			BIGINT,';
	$q .= 'ptAddlCommissionRate	BIGINT,';
	$q .= 'ptAddlCommission		BIGINT,';
	$q .= 'ptAddlNet				BIGINT,';
	$q .= 'ptAddlIPT				BIGINT,';
	$q .= 'ptAddOnCoverDescription	VARCHAR(200),';
	$q .= 'ptAddOnGrossIncIPT			BIGINT,';
	$q .= 'ptAddOnGross			BIGINT,';
	$q .= 'ptAddOnCommissionRate	BIGINT,';
	$q .= 'ptAddOnCommission		BIGINT,';
	$q .= 'ptAddOnNet				BIGINT,';
	$q .= 'ptAddOnIPTRate			BIGINT,';
	$q .= 'ptAddOnIPT				BIGINT,';
	$q .= 'ptClientDiscountRate	BIGINT,';
	$q .= 'ptClientDiscount		BIGINT,';
	$q .= 'ptEngineeringFeeDesc		VARCHAR(200),';
	$q .= 'ptEngineeringFee			BIGINT,';
	$q .= 'ptEngineeringFeeCommRate	BIGINT,';
	$q .= 'ptEngineeringFeeComm		BIGINT,';
	$q .= 'ptEngineeringFeeNet		BIGINT,';
	$q .= 'ptEngineeringFeeVATRate	BIGINT,';
	$q .= 'ptEngineeringFeeVAT		BIGINT,';
	$q .= 'ptBrokerFee				BIGINT,';
	$q .= 'ptBrokerFeeVATRate			BIGINT,';
	$q .= 'ptBrokerFeeVAT				BIGINT,';
	$q .= 'ptIntroducerCommRate		BIGINT,';
	$q .= 'ptIntroducerComm			BIGINT,';
	$q .= 'ptTotalGross			BIGINT,';
	$q .= 'ptTotalGrossIncIPT		BIGINT,';
	$q .= 'ptTotalCommission		BIGINT,';
	$q .= 'ptTotalNet				BIGINT,';
	$q .= 'ptTotalIPT				BIGINT,';
	$q .= 'ptClientSubTotal		BIGINT,';
	$q .= 'ptClientTotal			BIGINT,';
	$q .= 'ptBrokerSubTotal		BIGINT,';
	$q .= 'ptBrokerTotalPlusFees	BIGINT,';
	$q .= 'ptBrokerTotal			BIGINT,';
	$q .= 'ptInsCoTotal			BIGINT,';
	$q .= 'ptAddOnTotal			BIGINT,';
	$q .= 'ptTotalInstalmentComm	BIGINT,';
	$q .= 'ptDirectClientTotal	BIGINT,';
	$q .= 'ptDirectClientGrand	BIGINT,';
	$q .= 'ptDirectBrokerTotal	BIGINT,';
	$q .= 'ptDocm					INT,';
	$q .= 'ptReceiptDocm			INT,';
	$q .= 'ptClientTran			INT,';
	$q .= 'ptMainInsCoTran		INT,';
	$q .= 'ptAddOnInsCoTran		INT,';
	$q .= 'ptIntroducerTran		INT,';
	$q .= 'ptCreatedBy			INT,';
	$q .= 'ptCreatedOn			CHAR(14),';
	$q .= 'ptLastUpdateBy			INT,';
	$q .= 'ptLastUpdateOn			CHAR(14),';
	$q .= 'ptPostStatus			CHAR(1),';
	$q .= 'ptReversesTran			INT,';
	$q .= 'lastAccessTime			CHAR(14))';
	udbcreatetable( 'policyTransactions', $q );
	udbsettablefortransactions( 'policyTransactions' );
	$q = 'ALTER TABLE policyTransactions AUTO_INCREMENT = 1000000';
	$result = mysql_query( $q );

	if ($result == null) {
		exit( 'cat set auto increment on policy trans' );
	}

	udbcreateindex( 'policyTransactions', 'ptPolicyIndex', 'ptPolicy' );
	$q = '';
	$q .= 'pyCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'pyName			VARCHAR(50),';
	$q .= 'pyFromPolicy		BOOL,';
	$q .= 'pyDebit			BOOL,';
	$q .= 'pyReverseAs		INT,';
	$q .= 'pySequence		INT)';
	udbcreatetable( 'policyTransactionTypes', $q );
	$q = '';
	$q .= 'tsCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'tsName			VARCHAR(100),';
	$q .= 'tsSequence		INT)';
	udbcreatetable( 'policyTransStatus', $q );
	$q = '';
	$q .= 'ctCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'ctSysTran			INT,';
	$q .= 'ctClient			INT,';
	$q .= 'ctPolicy			INT,';
	$q .= 'ctDirect			BOOL,';
	$q .= 'ctCashBatch		INT,';
	$q .= 'ctCashBatchItem	INT,';
	$q .= 'ctJournal			INT,';
	$q .= 'ctTransType		CHAR(1),';
	$q .= 'ctInvoiceNo		INT,';
	$q .= 'ctPolicyTransType	INT,';
	$q .= 'ctBrokerRef		VARCHAR(100),';
	$q .= 'ctPolicyTran		INT,';
	$q .= 'ctTransDesc		VARCHAR(250),';
	$q .= 'ctChequeNo			VARCHAR(50),';
	$q .= 'ctPostingDate		DATE,';
	$q .= 'ctEffectiveDate	DATE,';
	$q .= 'ctAccountingYear	INT,';
	$q .= 'ctAccountingPeriod	INT,';
	$q .= 'ctHandler			INT,';
	$q .= 'ctPaymentMethod	INT,';
	$q .= 'ctOriginal			BIGINT,';
	$q .= 'ctPaid				BIGINT,';
	$q .= 'ctWrittenOff		BIGINT,';
	$q .= 'ctBalance			BIGINT,';
	$q .= 'ctPaidDate			DATE,';
	$q .= 'ctDirectPaidDate	DATE,';
	$q .= 'ctDocm				INT,';
	$q .= 'ctCreatedBy		INT,';
	$q .= 'ctCreatedOn		CHAR(14),';
	$q .= 'ctLastUpdateBy		INT,';
	$q .= 'ctLastUpdateOn		CHAR(14),';
	$q .= 'lastAccessTime		CHAR(14))';
	udbcreatetable( 'clientTransactions', $q );
	udbsettablefortransactions( 'clientTransactions' );
	$q = 'ALTER TABLE clientTransactions AUTO_INCREMENT = 9000000';
	$result = mysql_query( $q );

	if ($result == null) {
		exit( 'cat set auto increment on client trans' );
	}

	udbcreateindex( 'clientTransactions', 'ctClientIndex', 'ctClient' );
	$q = '';
	$q .= 'caCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'caType				CHAR(1),';
	$q .= 'caCashTran			INT,';
	$q .= 'caOtherTran		INT,';
	$q .= 'caPostingDate		DATE,';
	$q .= 'caAmount			BIGINT,';
	$q .= 'caPaymentMethod	INT,';
	$q .= 'caAccountingYear	INT,';
	$q .= 'caAccountingPeriod	INT,';
	$q .= 'caLastUpdateBy		INT,';
	$q .= 'caLastUpdateOn		CHAR(14))';
	udbcreatetable( 'clientTransAllocations', $q );
	udbsettablefortransactions( 'clientTransAllocations' );
	udbcreateindex( 'clientTransAllocations', 'caCashTranIndex', 'caCashTran' );
	udbcreateindex( 'clientTransAllocations', 'caOtherTranIndex', 'caOtherTran' );
	$q = '';
	$q .= 'itCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'itSysTran			INT,';
	$q .= 'itInsCo			INT,';
	$q .= 'itTransType		CHAR(1),';
	$q .= 'itInsCoRef			VARCHAR(100),';
	$q .= 'itChequeNo			VARCHAR(100),';
	$q .= 'itPaymentType		INT,';
	$q .= 'itPolicyTran		INT,';
	$q .= 'itTransDesc		VARCHAR(250),';
	$q .= 'itCoverDesc		TEXT,';
	$q .= 'itPostingDate		DATE,';
	$q .= 'itEffectiveDate	DATE,';
	$q .= 'itCashBatch		INT,';
	$q .= 'itCashBatchItem	INT,';
	$q .= 'itJournal			INT,';
	$q .= 'itAccountingYear	INT,';
	$q .= 'itAccountingPeriod	INT,';
	$q .= 'itPaidDate			DATE,';
	$q .= 'itPaidYear			INT,';
	$q .= 'itPaidPeriod		INT,';
	$q .= 'itDirect				INT,';
	$q .= 'itGross				BIGINT,';
	$q .= 'itCommission			BIGINT,';
	$q .= 'itCommissionRate		BIGINT,';
	$q .= 'itNet					BIGINT,';
	$q .= 'itGrossIPT				BIGINT,';
	$q .= 'itEngineeringFeeDesc			VARCHAR(200),';
	$q .= 'itEngineeringFee			BIGINT,';
	$q .= 'itEngineeringFeeCommRate	BIGINT,';
	$q .= 'itEngineeringFeeComm		BIGINT,';
	$q .= 'itEngineeringFeeNet		BIGINT,';
	$q .= 'itEngineeringFeeVATRate	BIGINT,';
	$q .= 'itEngineeringFeeVAT		BIGINT,';
	$q .= 'itAddlCoverDesc		VARCHAR(100),';
	$q .= 'itAddlGross			BIGINT,';
	$q .= 'itAddlCommissionRate	BIGINT,';
	$q .= 'itAddlCommission		BIGINT,';
	$q .= 'itAddlNet				BIGINT,';
	$q .= 'itAddlIPT				BIGINT,';
	$q .= 'itOriginal			BIGINT,';
	$q .= 'itPaid				BIGINT,';
	$q .= 'itWrittenOff		BIGINT,';
	$q .= 'itBalance			BIGINT,';
	$q .= 'itDocm				INT,';
	$q .= 'itCreatedBy		INT,';
	$q .= 'itCreatedOn		CHAR(14),';
	$q .= 'itLastUpdateBy		INT,';
	$q .= 'itLastUpdateOn		CHAR(14),';
	$q .= 'lastAccessTime		CHAR(14))';
	udbcreatetable( 'inscoTransactions', $q );
	udbsettablefortransactions( 'inscoTransactions' );
	$q = 'ALTER TABLE inscoTransactions AUTO_INCREMENT = 4000000';
	$result = mysql_query( $q );

	if ($result == null) {
		exit( 'cat set auto increment on insco trans' );
	}

	udbcreateindex( 'inscoTransactions', 'itInsCoIndex', 'itInsCo' );
	$q = '';
	$q .= 'iaCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'iaType				CHAR(1),';
	$q .= 'iaCashTran			INT,';
	$q .= 'iaOtherTran		INT,';
	$q .= 'iaAmount			BIGINT,';
	$q .= 'iaPaymentMethod	INT,';
	$q .= 'iaPostingDate		DATE,';
	$q .= 'iaAccountingYear	INT,';
	$q .= 'iaAccountingPeriod	INT,';
	$q .= 'iaLastUpdateBy		INT,';
	$q .= 'iaLastUpdateOn		CHAR(14))';
	udbcreatetable( 'inscoTransAllocations', $q );
	udbsettablefortransactions( 'inscoTransAllocations' );
	udbcreateindex( 'inscoTransAllocations', 'iaCashTranIndex', 'iaCashTran' );
	udbcreateindex( 'inscoTransAllocations', 'iaOtherTranIndex', 'iaOtherTran' );
	$q = '';
	$q .= 'rtCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'rtSysTran			INT,';
	$q .= 'rtIntroducer		INT,';
	$q .= 'rtTransType		CHAR(1),';
	$q .= 'rtDirect			INT,';
	$q .= 'rtPolicyTran		INT,';
	$q .= 'rtTransDesc		VARCHAR(250),';
	$q .= 'rtPostingDate		DATE,';
	$q .= 'rtEffectiveDate	DATE,';
	$q .= 'rtCashBatch		INT,';
	$q .= 'rtCashBatchItem	INT,';
	$q .= 'rtJournal			INT,';
	$q .= 'rtIntrodRef		VARCHAR(100),';
	$q .= 'rtChequeNo			VARCHAR(100),';
	$q .= 'rtPaymentType		INT,';
	$q .= 'rtAccountingYear	INT,';
	$q .= 'rtAccountingPeriod	INT,';
	$q .= 'rtCalcOn			BIGINT,';
	$q .= 'rtRate				BIGINT,';
	$q .= 'rtOriginal			BIGINT,';
	$q .= 'rtPaid				BIGINT,';
	$q .= 'rtWrittenOff		BIGINT,';
	$q .= 'rtBalance			BIGINT,';
	$q .= 'rtDocm				INT,';
	$q .= 'rtCreatedBy		INT,';
	$q .= 'rtCreatedOn		CHAR(14),';
	$q .= 'rtLastUpdateBy		INT,';
	$q .= 'rtLastUpdateOn		CHAR(14),';
	$q .= 'rtPaidDate			DATE,';
	$q .= 'rtPaidYear			INT,';
	$q .= 'rtPaidPeriod		INT,';
	$q .= 'lastAccessTime		CHAR(14))';
	udbcreatetable( 'introducerTransactions', $q );
	udbsettablefortransactions( 'introducerTransactions' );
	$q = 'ALTER TABLE introducerTransactions AUTO_INCREMENT = 3000000';
	$result = mysql_query( $q );

	if ($result == null) {
		exit( 'cat set auto increment on insco trans' );
	}

	udbcreateindex( 'introducerTransactions', 'rtIntroducerIndex', 'rtIntroducer' );
	$q = '';
	$q .= 'raCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'raType				CHAR(1),';
	$q .= 'raCashTran			INT,';
	$q .= 'raOtherTran		INT,';
	$q .= 'raAmount			BIGINT,';
	$q .= 'raPaymentMethod	INT,';
	$q .= 'raPostingDate		DATE,';
	$q .= 'raAccountingYear	INT,';
	$q .= 'raAccountingPeriod	INT,';
	$q .= 'raLastUpdateBy		INT,';
	$q .= 'raLastUpdateOn		CHAR(14))';
	udbcreatetable( 'introducerTransAllocations', $q );
	udbsettablefortransactions( 'introducerTransAllocations' );
	udbcreateindex( 'introducerTransAllocations', 'raCashTranIndex', 'raCashTran' );
	udbcreateindex( 'introducerTransAllocations', 'raOtherTranIndex', 'raOtherTran' );
	$q = '';
	$q .= 'baCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'baSysTran			INT,';
	$q .= 'baType				INT,';
	$q .= 'baTran				INT,';
	$q .= 'baDebit			BOOL,';
	$q .= 'baAmount			BIGINT,';
	$q .= 'baPostingRef		VARCHAR(50),';
	$q .= 'baDescription		TEXT,';
	$q .= 'baPaymentType		INT,';
	$q .= 'baPostingDate		DATE,';
	$q .= 'baAccountingYear	INT,';
	$q .= 'baAccountingPeriod	INT,';
	$q .= 'baCreatedBy		INT,';
	$q .= 'baCreatedOn		CHAR(14),';
	$q .= 'baLastUpdateBy		INT,';
	$q .= 'baLastUpdateOn		CHAR(14),';
	$q .= 'lastAccessTime		CHAR(14))';
	udbcreatetable( 'bankAccountTrans', $q );
	udbsettablefortransactions( 'bankAccountTrans' );
	$q = 'ALTER TABLE bankAccountTrans AUTO_INCREMENT = 1000000';
	$result = mysql_query( $q );

	if ($result == null) {
		exit( 'cat set auto increment on bank acc trans' );
	}

	$q = '';
	$q .= 'byCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'byName				VARCHAR(50),';
	$q .= 'byDebit			BOOL,';
	$q .= 'byAllowUserSelect	BOOL DEFAULT 0,';
	$q .= 'bySequence			INT)';
	udbcreatetable( 'bankTransTypes', $q );
	$q = '';
	$q .= 'aaCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'aaSysTran			INT,';
	$q .= 'aaType				CHAR(2),';
	$q .= 'aaTran				INT,';
	$q .= 'aaPostingDate		DATE,';
	$q .= 'aaEffectiveDate	DATE,';
	$q .= 'aaAccountingYear	INT,';
	$q .= 'aaAccountingPeriod INT,';
	$q .= 'aaCreatedBy		INT,';
	$q .= 'aaCreatedOn		CHAR(14),';
	$q .= 'aaLastUpdateBy		INT,';
	$q .= 'aaLastUpdateOn		CHAR(14),';
	$q .= 'lastAccessTime		CHAR(14))';
	udbcreatetable( 'accountingAudit', $q );
	udbsettablefortransactions( 'accountingAudit' );
	$q = 'ALTER TABLE accountingAudit AUTO_INCREMENT = 9000000';
	$result = mysql_query( $q );

	if ($result == null) {
		exit( 'cat set auto increment on audit' );
	}

	$q = '';
	$q .= 'jnCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'jnSysTran			INT,';
	$q .= 'jnType				CHAR(2),';
	$q .= 'jnMaster			INT,';
	$q .= 'jnNarrative		VARCHAR(200),';
	$q .= 'jnPostingDate		CHAR(14),';
	$q .= 'jnAccountingYear	INT,';
	$q .= 'jnAccountingPeriod	INT,';
	$q .= 'jnTran				INT,';
	$q .= 'jnAmount			BIGINT,';
	$q .= 'jnCreatedBy		INT,';
	$q .= 'jnCreatedOn		CHAR(14),';
	$q .= 'jnLastUpdateBy		INT,';
	$q .= 'jnLastUpdateOn		CHAR(14),';
	$q .= 'lastAccessTime		CHAR(14))';
	udbcreatetable( 'journals', $q );
	udbsettablefortransactions( 'journals' );
	$q = 'ALTER TABLE journals AUTO_INCREMENT = 9000000';
	$result = mysql_query( $q );

	if ($result == null) {
		exit( 'cat set auto increment' . udblasterror(  ) );
	}

	$q = '';
	$q .= 'btCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'btSysTran			INT,';
	$q .= 'btPayInSlip		VARCHAR(30),';
	$q .= 'btBatchDate		DATE,';
	$q .= 'btWhenPosted		CHAR(14),';
	$q .= 'btWhoPosted		INT,';
	$q .= 'btLocked			BOOL,';
	$q .= 'btAccountingYear	INT,';
	$q .= 'btAccountingPeriod	INT,';
	$q .= 'btTotal			BIGINT,';
	$q .= 'btEntered			BIGINT,';
	$q .= 'btRemaining		BIGINT,';
	$q .= 'btAllocated		BIGINT,';
	$q .= 'btUnallocated		BIGINT,';
	$q .= 'btLastUpdateBy		INT,';
	$q .= 'btLastUpdateOn		CHAR(14),';
	$q .= 'lastAccessTime		CHAR(14))';
	udbcreatetable( 'cashBatches', $q );
	udbsettablefortransactions( 'cashBatches' );
	$q = 'ALTER TABLE cashBatches AUTO_INCREMENT = 8000000';
	$result = mysql_query( $q );

	if ($result == null) {
		exit( 'cat set auto increment' . udblasterror(  ) );
	}

	$q = '';
	$q .= 'biCode		 		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'biBatch			INT,';
	$q .= 'biSequence			INT,';
	$q .= 'biPayeeType		CHAR(1),';
	$q .= 'biClient			INT,';
	$q .= 'biInsco			INT,';
	$q .= 'biIntroducer		INT,';
	$q .= 'biTrans			INT,';
	$q .= 'biItemName			VARCHAR(100),';
	$q .= 'biCheque			VARCHAR(40),';
	$q .= 'biSortCode			VARCHAR(20),';
	$q .= 'biPaymentMethod	INT,';
	$q .= 'biAmount			BIGINT,';
	$q .= 'biAllocated		BOOL,';
	$q .= 'biDateAllocated	CHAR(14),';
	$q .= 'biAllocatedBy		INT,';
	$q .= 'biLastUpdateBy		INT,';
	$q .= 'biLastUpdateOn		CHAR(14),';
	$q .= 'lastAccessTime		CHAR(14))';
	udbcreatetable( 'cashBatchItems', $q );
	udbsettablefortransactions( 'cashBatchItems' );
	$q = '';
	$q .= 'cpCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'cpName			VARCHAR(100),';
	$q .= 'cpSequence		INT)';
	udbcreatetable( 'cashPaymentMethods', $q );
	$q = '';
	$q .= 'afCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'afYear			INT,';
	$q .= 'afPeriod			INT,';
	$q .= 'afPeriodCode		INT UNIQUE,';
	$q .= 'afFromDate		DATE,';
	$q .= 'afToDate			DATE,';
	$q .= 'afClients			BIGINT,';
	$q .= 'afInsurers			BIGINT,';
	$q .= 'afCommPosted			BIGINT,';
	$q .= 'afFeesPosted			BIGINT,';
	$q .= 'afIntroducers		BIGINT,';
	$q .= 'afCommPaid			BIGINT,';
	$q .= 'afFeesPaid			BIGINT,';
	$q .= 'afOtherIncome		BIGINT,';
	$q .= 'afOtherCharges		BIGINT,';
	$q .= 'afBank				BIGINT,';
	$q .= 'afBankAccount		BIGINT,';
	$q .= 'afIBAOther			BIGINT,';
	$q .= 'afCommFees			BIGINT)';
	udbcreatetable( 'accountingFigures', $q );
	$q = '';
	$q .= 'ayCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'ayYear			INT),';
	$q .= 'ayName			VARCHAR(100),';
	$q .= 'ayFromDate		DATE,';
	$q .= 'ayToDate			DATE)';
	udbcreatetable( 'accountingYears', $q );
	$q = '';
	$q .= 'apCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'apYear			INT,';
	$q .= 'apPeriod			INT,';
	$q .= 'apName			VARCHAR(100),';
	$q .= 'apFromDate		DATE,';
	$q .= 'apToDate			DATE)';
	udbcreatetable( 'accountingPeriods', $q );
	$q = '';
	$q .= 'usCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'usLogin			VARCHAR(50),';
	$q .= 'usFirstName		VARCHAR(50),';
	$q .= 'usLastName		VARCHAR(50),';
	$q .= 'usInitials		VARCHAR(10),';
	$q .= 'usEmail			VARCHAR(100),';
	$q .= 'usPassword		VARCHAR(50),';
	$q .= 'usGroup			INT,';
	$q .= 'usHandler		BOOL,';
	$q .= 'usDisabled		BOOL,';
	$q .= 'usSysManager		BOOL,';
	$q .= 'usDepartment		INT)';
	udbcreatetable( 'users', $q );
	udbcreateindex( 'users', 'usEmailIndex', 'usEmail' );
	$q = '';
	$q .= 'ugCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'ugName			VARCHAR(50),';
	$q .= 'ugLevel			INT,';
	$q .= 'ugSequence		INT)';
	udbcreatetable( 'userGroups', $q );
	$q = '';
	$q .= 'loCode		INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'loWhen		TIMESTAMP,';
	$q .= 'loPage		VARCHAR(200),';
	$q .= 'loName		VARCHAR(200),';
	$q .= 'loURL		VARCHAR(200))';
	udbcreatetable( 'accesslog', $q );
	$q = '';
	$q .= 'syCode			INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,';
	$q .= 'sySiteName		VARCHAR(200),';
	$q .= 'syName			VARCHAR(200),';
	$q .= 'syBrokerVATRate	BIGINT,';
	$q .= 'syCompanyVATRate	BIGINT,';
	$q .= 'syNormalIPTRate	BIGINT,';
	$q .= 'syTravelIPTRate	BIGINT,';
	$q .= 'syAccountingYear		INT,';
	$q .= 'syAccountingPeriod	INT,';
	$q .= 'syPeriodFrom			DATE,';
	$q .= 'syPeriodTo			DATE)';
	$q .= 'syYearCode			INT,';
	$q .= 'syPeriodCode			INT,';
	$q .= 'syMaxUsers			INT';
	udbcreatetable( 'system', $q );
	echo 'DONE';
?>